### ISSUE TITLE
Force mobile theme on a desktop browser

### ISSUE THREAD

**Issue by manubirioukoff** [davidalger/CLS_DesignSwitcher#2]
Hi, 

You wrote in the module description 
"There is also a route to revert to the mobile theme (getDesktopToMobileUrl), although at this time it will not allow users of a desktop browser to view the mobile theme by clicking the link."

But is there a way to do this ? Viewing the mobile theme on a desktop browser ?

Thx :)

**Comment by davidalger** [comment]
@manubirioukoff Sorry… literally just saw this. It slipped by me. :/ Assuming you're using design exceptions to trigger the mobile theme (which is what this module was built around using) then you should be able to change the user agent of your browser to match a mobile device user agent. Or just set a design exception which triggers on something in your desktop browser's UA.
