### ISSUE TITLE
I get a fatal error

### ISSUE THREAD

**Issue by RoAndrei** [davidalger/CLS_DesignSwitcher#3]
this one: Fatal error: Uncaught exception 'Mage_Core_Exception' with message 'Module "CLS_DesignSwitcher" requires module "Enterprise_PageCache".. then nothing else works.

Any ideas?

**Comment by davidalger** [comment]
@RoAndrei It was built on EE 1.13, and it would seem you're running it on CE. Take a look at the "Compatibility" section in the README file for info on how to get it working on Community Edition. Cheers!
