### ISSUE TITLE
No link is showing in the footer.

### ISSUE THREAD

**Issue by 007kishore** [davidalger/CLS_DesignSwitcher#4]
I am using magento1.7 CE.
I have created a mobile theme named "iphone"(copying from the defalut magento).
 I have upload the required folder to its corresponding place. but the link is not coming in the footer. 
it says "Fatal error</b>:  Class 'Mage_Cls_Designswitcher_Helper_Data' not found"

But the class defined in helper  is ...
"class CLS_DesignSwitcher_Helper_Data extends Mage_Core_Helper_Abstract"
So why it is prepends with "Mage"
I don't understand what is the error ?
Can you suggest me how to fix this ?

**Comment by davidalger** [comment]
@007kishore It sounds like the module is not installed correctly, as the helper class prefix is not being used when the helper is instantiated. I am going to go ahead and close this out. It's not an issue with the module/sample code, and I am not in a good position to provide free support right now (as evidenced by my slow reply ;) )
